params:
  _target_: JacobianODE.models.mlp.MLP
  input_dim: null
  hidden_dim: [256, 1024, 2048, 2048] # *****
  num_layers: 4

  output_dim: null
  residuals: False
  dropout: 0.0
  activation: 'silu'
  # activation: 'relu'
  # activation: 'elu'